
export default {
  // common
  APPName: 'QKIDS',
  space: '  ',
  net_error_fresh: 'Network abnormal, please pull down refresh',
  and: 'and',
  tips: 'Tips',
  ignore: 'Ignore',
  back: 'Back',
  practice: 'practice',
  test: 'test',
  finish: 'Done',
  cancel: 'Cancel',
  confirm: 'Confirm',
  totalScore: 'Score:  ',
  yesterday: 'yesterday',
  today: 'today',
  tomorrow: 'tomorrow',
  girl: 'girl',
  boy: 'boy',
  confirmExit: 'Are you sure Exit ?',
  enterRoom: 'Enter the classroom only {0} minutes before class begins',
  enterRoomTitle: 'Enter Room',
  checkDetail: 'checkDetail',
  backHome: 'backHome',
  difficulty: 'difficulty ',
  // authenticate
  auth_PlaceHolder1: 'Enter mobile phone number',
  auth_PlaceHolder2: 'Enter Password, at least six',
  auth_PlaceHolder3: 'Enter code',
  auth_PlaceHolder4: 'Enter new password',
  auth_PlaceHolder5: 'SMS code',
  auth_GetSMS: 'Send',
  auth_ReSendSMS: 'Resend {0}s',
  auth_RememberPwd: 'Remember password',
  auth_ForgetPwd: 'Unable to Log in?',
  auth_LoginSMS: 'Log in via SMS verification code',
  auth_LoginPwd: 'Log in via password',
  auth_Register: 'Sign up with mobile',
  auth_Login: 'Log in',
  auth_RegisterTitle: 'Register',
  auth_tips: 'Tips: if your mobile not register, it will be automatically registered when Log in',
  auth_userTerms: 'User Terms',
  auth_privacyPolicy: 'Privacy policy',
  auth_agree: 'Register/Login means consent',
  auth_errorPhoneNumber: 'phone Number Error',
  auth_modifyPwd: 'Password Reset',
  // home
  home: 'home',
  home_course: 'courses',
  home_service: 'service',
  home_current_level: 'Current Level :  ',
  home_schedule: 'SCHEDULE',
  home_appointment: 'RESERVED',
  home_all_levels: 'ALL COURSES LEVEL',
  // lesson Detail
  lessonDetail_summary: 'Summary',
  lessonDetail_destination: 'Destination',
  lessonDetail_sentencePattern: 'Key Sentences',
  lessonDetail_culture: 'Culture',
  lessonDetail_vocabulary: 'Vocabulary(Image is clickable)',
  lessonDetailPre: 'Preview',
  lessonDetailTitle: 'LessonDetails',
  lessonDetailAfter: 'Homework',
  lessonDetailUnitText: 'UnitText',
  lessonDetailUnitReview: 'UnitReview',
  lessonDetailUnlockGift: 'UnLock',
  lessonDetailVideo: 'Flash',
  lessonDetailPreviewVideo: 'Rob to see',
  lessonDetailVideoLockTips: 'Complete homework to unlock the video',
  // lessonState
  lessonState_skip: 'skip',
  lessonState_booked: 'booked',
  // preview
  lesson_preview_title: 'Accuracy',
  lesson_preview_desc: 'familiar with the content of the course',
  lesson_preview_button_start: 'Preview Test',
  lesson_preview_button_review: 'Review Preview Test',
  lesson_preview_download: 'Download lecture',
  lesson_preview_video: 'PREVIEW VIDEO',
  // homework
  lesson_homework_title: 'Accuracy',
  lesson_homework_desc: 'The more practice, the better you can do!',
  lesson_homework_button_start: 'Do homework',
  lesson_homework_button_review: 'Review homework',
  lesson_homework_download: 'Download workbook',
  // homework_image:
  homework_listen: 'listen',
  homework_vocabulary: 'vocabulary',
  homework_read: 'read',
  homework_speak: 'speak',
  homework_grammar: 'grammar',
  homework_spelling: 'spell',
  homework_sightwords: 'Sigh words',
  // unit Test
  lesson_unit_disable_tips: 'come back to the test after this lesson!',
  lesson_unit_able_tips: 'All right, how are you doing in this unit',
  lesson_unit_preview_tips: 'Stage small review, random question practice more do not repeat',
  lesson_upgrade_review: 'Upgrade Review',
  lesson_upgrade_test: 'Upgrade Test',
  // upgrade
  upgrade_test_title: 'Test evaluation: ',
  upgrade_test_des1: 'Congratulations on your upgrade!',
  upgrade_test_des2: 'QKids aims to make every child learn happily and efficiently',
  upgrade_test_des3: 'The overall situation is good, and it is recommended to enter the next level.',
  upgrade_test_des4: 'The result of the test has a little regret, some knowledge is not enough',
  upgrade_test_des5: 'Looking forward to your excellent performance in the course.',
  upgrade_test_des6: 'Looking forward to your continuous growth in the long interesting course!',
  upgrade_test_des7: 'But, I believe you can do better!We look forward to your continuous growth and progress in the interesting courses.',
  upgrade_test_des8: 'Some knowledge points need to be consolidated. The exercises in the following courses are suggested to be redone:',
  upgrade_test_des9: 'Some knowledge points need to be consolidated. The following exercises need to be redone',
  upgrade_test_des10: 'Some knowledge points are not well mastered. It is suggested to make a new appointment for the following courses:',
  upgrade_test_des11: 'Some knowledge points are not well mastered, and the following courses need to be rescheduled:',
  upgrade_test_des12: 'Some knowledge points are not well mastered, and the following courses need to be practised:',
  upgrade_next: ' next level',
  upgrade_review_test: 'Look over tests',
  // error_code
  error_invalid_mobile: 'The mobile phone number format is not correct',
  error_account: 'Please enter the account',
  error_password: 'Password length is 6-30 bits',
  error_invalid_password: 'Password length is 6-30 bits and can only contain letters, Numbers, "-" and "_"',
  error_verify: 'The verification code is four digits',
  error_invalid_nickname: 'Nicknames can only contain letters and Numbers',
  error_net_anomalies: 'network anomalies',
  error_net_anomalies_retry: 'network anomalies，please retry',
  error_enter_room_fail: 'Failure to enter the room',
  error_enter_room_fail_retry: 'Failure to enter the room，please retry',
  // setting:
  set_title: 'Setting',
  set_performance_test: 'Performance Test',
  set_send_log: 'Send Log',
  set_log_out: 'Log Out',
  set_nickname: 'NickName',
  set_sex: 'Sex',
  set_age: 'Age',
  // test
  test_lose_desc1: 'test will lose desc1',
  test_lose_desc2: 'test will lose desc2',
  test_lose_desc3: 'test will lose desc3',
  test_lose_desc4: 'test will lose desc4',
  test_complete_slogan_desc1: 'test_complete_slogan_desc1',
  test_complete_slogan_desc2: 'test_complete_slogan_desc2',
  test_complete_slogan_desc3: 'test_complete_slogan_desc3',
  test_complete_slogan_desc4: 'test_complete_slogan_desc4',
  test_complete_slogan_desc5: 'test_complete_slogan_desc5',
  test_complete_slogan_desc6: 'test_complete_slogan_desc6',
  test_answer: 'Look At answer',
  test_submit: 'Submit',
  test_next: 'Next',
  // roomType
  roomType_all: 'general',
  roomType_6: '6 mates',
  roomType_4: '4 mates',
  roomType_2: '2 mates',
  roomType_1: 'single',
  // init level
  init_level: 'Please first complete the learning information, after receiving the grading notice, you can make an appointment for the class!',
};
